version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      avalonia:
        patterns:
          - avalonia*
      microsoft-extensions:
        patterns:
          - microsoft.extensions.*
      serilog:
        patterns:
          - serilog*
      xunit:
        patterns:
          - xunit*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

